// SPDX-FileCopyrightText: 2026 British Club Challenge authors
// SPDX-License-Identifier: MPL-2.0
/**
 * Per-request work budget for the four pure status transitions
 * (confirm / reopen / cancel / uncancel) — issue #274.
 *
 * This is the executable form of two acceptance criteria for the
 * round-transition module:
 *
 *   2. a transition reads `rounds/{id}.json` ONCE and resolves the caller ONCE
 *   3. the republish (`updateRoundsIndex`) happens inside the module, and only
 *      when the transition actually succeeded
 *
 * The counts asserted here are the TARGET (1 read, 1 caller, 1 republish), not
 * today's behaviour. On unrefactored `main` every handler resolves the caller
 * twice and reads the round blob three times — once in the handler's own
 * `assertManageableRound`, once in `transition()`'s repeat of it, and once
 * inside `withPrivateLease` (roundsMutate.ts:460, :467). So the read/caller
 * expectations in the first describe FAIL on `main` with `expected 3 to be 1`
 * and `expected 2 to be 1`; the republish expectations already pass, because
 * the refactor moves WHERE the republish happens, not WHETHER.
 *
 * Two-sided on purpose: a mis-scoped path filter would count nothing and turn
 * `toBe(1)` into a plausible-looking `expected 0 to be 1` that stays red after
 * the refactor. The `toBeGreaterThanOrEqual(1)` guards run first and fail
 * loudly on a vacuous counter — and they hold both before (3/2) and after
 * (1/1) the refactor.
 */
import { randomUUID } from "node:crypto";
import type { HttpResponseInit } from "@azure/functions";
import type { Round, RoundStatus, User } from "@bccweb/types";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { invoke, makeAuthRequest } from "../../__tests__/helpers/api.js";
import { resetAllBuckets } from "../../lib/rateLimit.js";
import {
  makeRound,
  makeUser,
  readPrivateJson,
  writePrivateJson,
} from "../../__tests__/helpers/seed.js";

// ─── Counting seams ───────────────────────────────────────────────────────────

/**
 * Armed only for the duration of the measured request, so the blob and auth
 * traffic generated by the fixtures (makeRound and makeUser both drive real
 * handlers) is never counted.
 */
const meter = vi.hoisted(() => ({
  /** `rounds/{id}.json` for the round under test, or null when disarmed. */
  roundPath: null as null | string,
  reads: 0,
  callers: 0,
}));

// Wraps the REAL readJson — a bare vi.mock here would break every blob read in
// the suite. Filters on the third arg (the blob path, blobJson.ts:102-106) so
// reads of sites/, seasons/, clubs/ and config.json are ignored and the count
// stays meaningful as unrelated handlers grow.
vi.mock("../../lib/blobJson.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../../lib/blobJson.js")>();
  return {
    ...actual,
    readJson: async <T>(...args: Parameters<typeof actual.readJson<T>>): Promise<T> => {
      if (meter.roundPath !== null && args[2] === meter.roundPath) meter.reads += 1;
      return actual.readJson(...args);
    },
  };
});

// The four handlers import getCallerIdentity from ../lib/auth.js (auth.ts:247).
vi.mock("../../lib/auth.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../../lib/auth.js")>();
  return {
    ...actual,
    getCallerIdentity: (
      ...args: Parameters<typeof actual.getCallerIdentity>
    ): ReturnType<typeof actual.getCallerIdentity> => {
      if (meter.roundPath !== null) meter.callers += 1;
      return actual.getCallerIdentity(...args);
    },
  };
});

// Same precedent as completeRoundAccountedFor.test.ts (commit 94fd24d): mock the
// module, keep the real implementation, assert on the call. Calling through
// means the public rounds.json is still genuinely republished.
vi.mock("../../lib/recompute.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../../lib/recompute.js")>();
  return { ...actual, updateRoundsIndex: vi.fn(actual.updateRoundsIndex) };
});

import { updateRoundsIndex } from "../../lib/recompute.js";
import "../roundsMutate.js";

const republish = vi.mocked(updateRoundsIndex);

// ─── The four transitions ─────────────────────────────────────────────────────

interface TransitionSpec {
  /** Registered handler name (roundsMutate.ts:1502, :1516, :1537, :1544). */
  readonly handler: string;
  /** A status the transition accepts — the success path. */
  readonly from: RoundStatus;
  readonly to: RoundStatus;
  /** A status the transition rejects — the 409 path. */
  readonly conflictFrom: RoundStatus;
}

const SPECS: readonly TransitionSpec[] = [
  { handler: "confirmRound", from: "Proposed", to: "Confirmed", conflictFrom: "Confirmed" },
  { handler: "reopenBrief", from: "BriefComplete", to: "Confirmed", conflictFrom: "Confirmed" },
  { handler: "cancelRound", from: "Confirmed", to: "Cancelled", conflictFrom: "Cancelled" },
  { handler: "uncancelRound", from: "Cancelled", to: "Proposed", conflictFrom: "Proposed" },
];

const CASES = SPECS.map((spec) => [spec.handler, spec] as const);

// ─── Fixtures ─────────────────────────────────────────────────────────────────

/**
 * Seed a round parked at `status`. Forced by a direct blob write because
 * `makeRound` reaches its statuses through `transitionRound` (seed.ts:377) —
 * the very machinery being measured here.
 */
async function seedRoundAt(status: RoundStatus): Promise<Round> {
  const created = await makeRound({
    organisingClubId: randomUUID(),
    organisingClubName: "Test Club",
  });

  const round = await readPrivateJson<Round>(`rounds/${created.id}.json`);
  if (!round) throw new Error(`Round ${created.id} missing`);

  round.status = status;
  // Production sets isLocked at Locked and nowhere else (roundsMutate.ts:1457).
  round.isLocked = status === "Locked";
  await writePrivateJson(`rounds/${created.id}.json`, round);

  return round;
}

interface Measured {
  res: HttpResponseInit;
  reads: number;
  callers: number;
}

/**
 * Run one request with the meter armed, and snapshot the counters the instant
 * it returns — before any assertion read can perturb them.
 *
 * Deliberately no `dryRun` query: reopenBrief's dryRun branch takes its own
 * read-and-return path (roundsMutate.ts:806-824) and would hide the double
 * charge this file exists to measure.
 */
async function measure(
  user: Pick<User, "id" | "email">,
  spec: TransitionSpec,
  roundId: string,
): Promise<Measured> {
  meter.reads = 0;
  meter.callers = 0;
  meter.roundPath = `rounds/${roundId}.json`;
  republish.mockClear();
  try {
    const res = await invoke(
      spec.handler,
      makeAuthRequest(user.id, user.email, { method: "POST", params: { id: roundId } }),
    );
    return { res, reads: meter.reads, callers: meter.callers };
  } finally {
    meter.roundPath = null;
  }
}

// ─── Criterion 2: one read, one caller resolution ─────────────────────────────

describe("round transitions — per-request work budget (issue 274)", () => {
  beforeEach(() => resetAllBuckets());

  it.each(CASES)(
    "%s: reads rounds/{id}.json once and resolves the caller once",
    async (_name, spec) => {
      const round = await seedRoundAt(spec.from);
      const { user } = await makeUser({ roles: ["Admin"] });

      const { res, reads, callers } = await measure(user, spec, round.id);

      expect(res.status).toBe(200);

      // Vacuity guards. A wrong id in the path filter counts nothing, and
      // `expected 0 to be 1` below would masquerade as the intended red. These
      // hold at today's 3/2 and at the post-refactor 1/1.
      expect(reads).toBeGreaterThanOrEqual(1);
      expect(callers).toBeGreaterThanOrEqual(1);

      // Soft, so a single run reports BOTH observed numbers rather than
      // aborting on the first mismatch.
      expect.soft(reads).toBe(1);
      expect.soft(callers).toBe(1);
    },
  );
});

// ─── Criterion 3: republish exactly once, and only on success ─────────────────

describe("round transitions — republish (issue 274)", () => {
  beforeEach(() => resetAllBuckets());

  it.each(CASES)("%s: republishes the updated round exactly once", async (_name, spec) => {
    const round = await seedRoundAt(spec.from);
    const { user } = await makeUser({ roles: ["Admin"] });

    const { res } = await measure(user, spec, round.id);

    expect(res.status).toBe(200);
    expect(republish).toHaveBeenCalledTimes(1);
    // The UPDATED round, not the pre-transition one — otherwise rounds.json
    // would republish the stale status.
    expect(republish).toHaveBeenCalledWith(
      expect.objectContaining({ id: round.id, status: spec.to }),
    );
  });

  it.each(CASES)("%s: does not republish when the transition 409s", async (_name, spec) => {
    const round = await seedRoundAt(spec.conflictFrom);
    const { user } = await makeUser({ roles: ["Admin"] });

    const { res } = await measure(user, spec, round.id);

    expect(res.status).toBe(409);
    expect(republish).not.toHaveBeenCalled();
    // And the round is untouched, so a passing "not called" cannot be an
    // artefact of the request failing earlier than the status gate.
    expect((await readPrivateJson<Round>(`rounds/${round.id}.json`))?.status).toBe(
      spec.conflictFrom,
    );
  });
});
